### PR TITLE
Use train configuration to start jobs

### PR DESCRIPTION
**Pull request by mpuccio**
Hi Christian,

thanks for your nice work! I added a small change that makes my life easier when I have to run jobs on small samples with the same configuration I use on the train.
I am no python expert and I tried to implement the thing consistently with what you did: if you find something strange tell me please!

Cheers,
Max

### CODE REVIEW

**Comment by cbourjau** [comment]
Hi Max,

this looks great, thank you very much! I didn't even know of that this was so easily possible! Just one remark: is there a reason that you require the flag `--use_train_conf`? I would ideally prefer this to be inferred from the "project directory" having either a `ConfigureWagon.C` __or__ a `MLTrainDefinition.cfg` and throwing an exception if it finds both or neither. After all, if one wants to develop on the two kinds in parallel, one could just make a second "project folder". Or am I overlooking your use case somehow? 

Cheers,
Christian

**Comment by mpuccio** [comment]
Hi Christian,
that's a good idea, I tried to implement it. To do that I had to add a field to the argparse namespace, that it is the fastest thing I could figure out. Maybe there is a more elegant solution, I let you judge!

Cheers,
Max

**Comment by cbourjau** [comment]
Looks good! I am also thinking about adding an import option for creating a new project folder. Something like:

```bash
$ nitty new myPbPbAnalysis --train="CF_PbPb" --run=3506
```

Thanks again for this patch!

**Comment by mpuccio** [comment]
That would be a very nice feature! Thanks a lot!

**Pull request merged**
