### PR TITLE
Add aliphysics_version argument

### PR DESCRIPTION
**Pull request by lbariogl**
Add the possibility to choose the version of aliphysics (only in grid mode) with the argument `--aliphysics_version`. It  checks wether the version has been deployed: if not, an error is raised.

### CODE REVIEW

**Comment by lbariogl** [comment]
I found a bug that I need to fix first

**Comment by cbourjau** [comment]
Any updates on this? This is a feature I wanted to add for a while. Let me know if you need some help about the inner workings of nittygriddy.

**Comment by lbariogl** [comment]
Apparently there was no bug.
In order to test my feature, I was using the comman `nitty run grid <listname> --aliphysics_version <aliphysics_version>`, interrupting it immediatly after the beginning of the execution and repeating the same command. I was getting the error `TypeError: coercing to Unicode: need string or buffer, NoneType found`.
I have just realised that I get the same errore indipendently from the `--aliphysics_version` argument. The cause was that the two commands were used two close to each other.
Therefore, I think that it should be ok.

**Comment by cbourjau** [comment]
Yes, that is a very unhelpful error and should fixed. When you do `run`, nittygriddy creates a folder with a time stamp that only resolves in minutes. So if you run the command again within one minute there is already an existing folder. I will create an issue to fix about this. Thanks for pointing it out!

**Comment by cbourjau** [comment]
Thanks again for this PR. I finally got around to take it for a spin. Sorry that it took so long!

**Comment by lbariogl** [comment]
No problem! :)

**Pull request merged**
